me-advert/console/views/client.py
# -*- coding: utf-8 -*-

from __future__ import division

__author__ = 'ogaidukov'

from datetime import datetime
from calendar import timegm
from collections import defaultdict
from flask import request, Blueprint, render_template, redirect, url_for, jsonify
from flask.ext.login import login_required, current_user
from sqlalchemy import func
from sqlalchemy.orm import joinedload
from sqlalchemy.orm.exc import NoResultFound
from console import local_tz, utc_tz, redirectors
from console.lib import funcs
from commonlib.model import Campaign, Creative, Counter, AdLog, Person, Organization, Site
from commonlib.database import session


client_bp = Blueprint('client', __name__)


@client_bp.route("/overview")
@login_required
def overview():
    org = current_user.person.organization
    if not org:
        return render_template('critical_error.html')

    active_campaigns = Campaign.query \
        .join(Organization.campaigns,
              Organization.persons) \
        .filter(Campaign.state == 'active',
                Person.id == current_user.person.id)\
        .count()
    inactive_campaigns = Campaign.query \
        .join(Organization.campaigns,
              Organization.persons) \
        .filter(Campaign.state.in_(['paused', 'completed']),
                Person.id == current_user.person.id)\
        .count()

    archived_campaigns = Campaign.query \
        .join(Organization.campaigns,
              Organization.persons) \
        .filter(Campaign.state == 'archived',
                Person.id == current_user.person.id)\
        .count()

    query_template = session.query(func.sum(AdLog.value)) \
        .join(Organization.campaigns,
              Organization.persons) \
        .join(Campaign.creatives) \
        .join(Creative.counters) \
        .join(Counter.logs) \
        .filter(Person.id == current_user.person.id,
                Campaign.state != 'archived')

    total_impressions = query_template \
        .filter(Person.id == current_user.person.id,
                AdLog.record_type == 'impr') \
        .first()[0]

    total_clicks = query_template \
        .filter(Person.id == current_user.person.id,
                AdLog.record_type == 'clck') \
        .first()[0]

    try:
        ctr = '{0:0.02f}'.format(total_clicks / total_impressions * 100.0)
    except (ZeroDivisionError, TypeError):
        ctr = '{0:0.02f}'.format(0.0)

    staff_raw = Person.query \
        .filter(Organization.id == org.id) \
        .join(Organization.persons) \
        .order_by('surname') \
        .all()
    staff = []
    for st in staff_raw:
        staff.append(u'{} {}'.format(st.first_name, st.surname))
    return render_template('client/overview.html',
                           org=org,
                           active_campaigns=active_campaigns,
                           inactive_campaigns=inactive_campaigns,
                           archived_campaigns=archived_campaigns,
                           staff=', '.join(staff),
                           total_impressions=funcs.format_decimal(total_impressions) if total_impressions else 0,
                           total_clicks=funcs.format_decimal(total_clicks) if total_clicks else 0,
                           ctr=ctr)


@client_bp.route("/campaigns")
@login_required
def campaigns():
    mix = defaultdict(dict)

    query_template = session.query(Campaign, func.sum(AdLog.value)) \
        .join(Organization.persons,
              Organization.campaigns) \
        .join(Campaign.creatives) \
        .join(Creative.counters) \
        .join(Counter.logs) \
        .filter(Person.id == current_user.person.id,
                Campaign.state != 'archived') \
        .group_by(Campaign)

    impressions = query_template \
        .filter(AdLog.record_type == 'impr') \
        .all()
    for impr in impressions:
        campaign = impr[0]
        val = impr[1]
        mix[campaign.id].update({'id': campaign.id,
                                 'name': campaign.name,
                                 'state': funcs.states[campaign.state],
                                 'impr': val})

    clicks = query_template \
        .filter(AdLog.record_type == 'clck') \
        .all()
    for clck in clicks:
        campaign = clck[0]
        val = clck[1]
        mix[campaign.id].update({'campaign_id': campaign.id,
                                 'name': campaign.name,
                                 'state': funcs.states[campaign.state],
                                 'clck': val})
    data = mix.values()
    for d in data:
        try:
            d['ctr'] = '{0:0.02f}'.format(d['clck'] / d['impr'] * 100.0)
        except (ZeroDivisionError, TypeError, KeyError):
            d['ctr'] = '{0:0.02f}'.format(0.0)
        d['impr'] = funcs.format_decimal(d['impr'])
        d['clck'] = funcs.format_decimal(d['clck'])
    #if len(data) == 0:
    #    return ''
    return render_template('client/campaigns.html', data=data)


@client_bp.route("/creatives_by_campaign/<int:campaign_id>")
@login_required
def creatives_by_campaign(campaign_id):
    try:
        campaign = Campaign.query \
            .join(Organization.persons, Organization.campaigns) \
            .filter(Campaign.id == campaign_id,
                    Campaign.state != 'archived',
                    Person.id == current_user.person.id) \
            .one()
    except NoResultFound:
        return redirect(url_for(redirectors[current_user.person.role]))

    creative_mix = defaultdict(dict)

    creatives_list = Creative.query \
        .join(Campaign.creatives) \
        .options(joinedload(Creative.creative_format)) \
        .filter(Campaign.id == campaign_id) \
        .all()
    for creative in creatives_list:
        creative_mix[creative.id].update({'campaign_id': creative.campaign.id,
                                         'creative_id': creative.id,
                                         'creative_name': creative.name,
                                         'creative_format': creative.creative_format,
                                         'frequency': creative.frequency,
                                         'target_impr': creative.target_impressions})

    if len(creatives_list) == 0:
        return render_template('client/no_creatives_yet.html',
                               campaign_name=campaign.name)

    query_template = session.query(Creative, func.sum(AdLog.value)) \
        .join(Campaign.creatives) \
        .join(Creative.counters) \
        .join(Counter.logs) \
        .filter(Campaign.id == campaign_id,
                Campaign.state != 'archived') \
        .group_by(Creative)

    impressions = query_template \
        .filter(AdLog.record_type == 'impr') \
        .all()
    for summary in impressions:
        creative = summary[0]
        val = summary[1]
        creative_mix[creative.id].update({'impr': val})

    clicks = query_template \
        .filter(AdLog.record_type == 'clck') \
        .all()
    for summary in clicks:
        creative = summary[0]
        val = summary[1]
        creative_mix[creative.id].update({'clck': val})

    creatives = creative_mix.values()
    for d in creatives:
        try:
            d['ctr'] = '{0:0.02f}'.format(d['clck'] / d['impr'] * 100.0)
        except TypeError:
            d['ctr'] = '{0:0.02f}'.format(0.0)
        except KeyError:
            d['ctr'] = u'нет'
        except ZeroDivisionError:
            d['ctr'] = '&infin;'
        try:
            reach = funcs.reach(d['target_impr'], d['impr'], d['frequency'])
            del d['frequency']
            d['reach'] = funcs.format_decimal('{0:0.0f}'.format(reach))
        except (ZeroDivisionError, TypeError):
            d['reach'] = '{0:0.0f}'.format(0.0)
        except KeyError:
            d['reach'] = u'нет'
        try:
            d['target_impr'] = funcs.format_decimal(d['target_impr'])
        except KeyError:
            pass
        try:
            d['impr'] = funcs.format_decimal(d['impr'])
        except KeyError:
            pass
        try:
            d['clck'] = funcs.format_decimal(d['clck'])
        except KeyError:
            pass

    enabled_sites = Site.query \
        .join(Campaign.sites) \
        .filter(Campaign.id == campaign_id,
                Site.is_hit == True) \
        .all()

    return render_template('client/creatives_by_campaign.html',
                           campaign=campaign,
                           creatives=creatives,
                           sites=enabled_sites)


@client_bp.route("/stats_by_campaign/<int:campaign_id>")
@login_required
def stats_by_campaign(campaign_id):
    try:
        campaign = Campaign.query \
            .join(Organization.persons, Organization.campaigns) \
            .filter(Campaign.id == campaign_id,
                    Person.id == current_user.person.id) \
            .one()
    except NoResultFound:
        return redirect(url_for(redirectors[current_user.person.role]))
    return render_template('client/graph_by_campaign.html',
                           campaign=campaign)


@client_bp.route("/stats_graph_of_campaign_ajax/<int:campaign_id>", methods=["GET"])
@login_required
def stats_graph_of_campaign_ajax(campaign_id):
    campaign_query = Campaign.query \
        .filter(Campaign.id == campaign_id)
    if current_user.person.role == 'customer':
        campaign_query = campaign_query \
            .join(Organization.campaigns,
                  Organization.persons) \
            .filter(Person.id == current_user.person.id)
    try:
        campaign_query.one()
    except NoResultFound:
        return jsonify()

    query_template = session.query(func.sum(AdLog.value)) \
        .join(Organization.campaigns) \
        .join(Campaign.creatives) \
        .join(Creative.counters) \
        .join(Counter.logs) \
        .filter(Campaign.id == campaign_id,
                Campaign.state != 'archived')
    scale = request.args.get('scale', 'day')

me-advert/console/views/stats.py
# -*- coding: utf-8 -*-

from __future__ import division

__author__ = 'ogaidukov'

from datetime import datetime, timedelta
from collections import defaultdict
from itertools import tee, izip
from flask import Blueprint
from flask import request, render_template, redirect, jsonify, url_for
from flask.ext.login import login_required, current_user
from console import utc_tz, local_tz
from console.lib.identity import manager_required
from console import redirectors
from sqlalchemy import func
from sqlalchemy.orm import joinedload
from sqlalchemy.orm.exc import NoResultFound
from commonlib.database import session
from commonlib.model import Campaign, Creative, Counter, AdLog


stats_bp = Blueprint('stats', __name__)


@stats_bp.route("/stats_by_campaign/<int:campaign_id>")
@login_required
@manager_required
def stats_by_campaign(campaign_id):
    try:
        campaign = session.query(Campaign) \
            .options(joinedload(Campaign.organization)) \
            .filter(Campaign.id == campaign_id,
                    Campaign.state != 'archived')\
            .one()
    except NoResultFound:
        return redirect(url_for(redirectors[current_user.person.role]))

    return render_template('stats/stats_by_campaign.html',
                           campaign=campaign)


@stats_bp.route("/stats_by_creative/<int:creative_id>")
@login_required
@manager_required
def stats_by_creative(creative_id):
    try:
        creative = session.query(Creative) \
            .options(joinedload(Creative.campaign,
                                Campaign.organization)) \
            .join(Campaign.creatives) \
            .filter(Creative.id == creative_id,
                    Campaign.state != 'archived')\
            .one()
    except NoResultFound:
        return redirect(url_for(redirectors[current_user.person.role]))

    return render_template('stats/stats_by_creative.html',
                           creative=creative)


@stats_bp.route("/stats_by_counter/<int:counter_id>")
@login_required
@manager_required
def stats_by_counter(counter_id):
    try:
        counter = session.query(Counter) \
            .options(joinedload(Counter.creative,
                                Creative.campaign,
                                Campaign.organization),
                     joinedload(Counter.contractor)) \
            .join(Campaign.creatives) \
            .join(Creative.counters) \
            .filter(Counter.id == counter_id,
                    Campaign.state != 'archived')\
            .one()
    except NoResultFound:
        return redirect(url_for(redirectors[current_user.person.role]))

    return render_template('stats/stats_by_counter.html',
                           counter=counter)


@stats_bp.route("/stats_by_campaign_ajax/<int:campaign_id>", methods=["GET"])
@login_required
@manager_required
def stats_by_campaign_ajax(campaign_id):
    query_template = session.query(Campaign) \
        .filter(Campaign.id == campaign_id)
    return prepare_stats(query_template)


@stats_bp.route("/stats_by_creative_ajax/<int:creative_id>", methods=["GET"])
@login_required
@manager_required
def stats_by_creative_ajax(creative_id):
    query_template = session.query(Creative) \
        .filter(Creative.id == creative_id)
    return prepare_stats(query_template)


@stats_bp.route("/stats_by_counter_ajax/<int:counter_id>", methods=["GET"])
@login_required
@manager_required
def stats_by_counter_ajax(counter_id):
    query_template = session.query(Counter) \
        .filter(Counter.id == counter_id)
    return prepare_stats(query_template)


def prepare_stats(query_template):
    start_datetime = request.args.get('start_datetime', '01.01.1970 00:00')
    end_datetime = request.args.get('end_datetime', '01.01.2970 00:00')
    try:
        start_datetime = datetime.strptime(start_datetime, '%d.%m.%Y %H:%M')
        end_datetime = datetime.strptime(end_datetime, '%d.%m.%Y %H:%M')
    except ValueError:
        return jsonify()

    scale = request.args.get('scale', 'day')
    if scale == 'hour':
        sqla_timedate_field = AdLog.date_to_hour_stamp
        datetime_interval = timedelta(hours=1)
    elif scale == 'day':
        sqla_timedate_field = AdLog.date_stamp
        datetime_interval = timedelta(days=1)
    else:
        return jsonify()

    query_template = query_template \
        .join(Campaign.creatives) \
        .join(Creative.counters) \
        .join(Counter.logs) \
        .filter(Campaign.state != 'archived',
                sqla_timedate_field.between(start_datetime, end_datetime))

    summary = defaultdict(dict)

    imprs_data = query_template \
        .with_entities(sqla_timedate_field, func.sum(AdLog.value)) \
        .filter(AdLog.record_type == 'impr') \
        .group_by(sqla_timedate_field) \
        .all()
    for k, v in imprs_data:
        if k:
            summary[k]['imprs'] = v

    clcks_data = query_template \
        .with_entities(sqla_timedate_field, func.sum(AdLog.value)) \
        .filter(AdLog.record_type == 'clck') \
        .group_by(sqla_timedate_field) \
        .all()
    for k, v in clcks_data:
        if k:
            summary[k]['clcks'] = v

    for k in summary.itervalues():
        try:
            k['ctr'] = '{0:0.02f}'.format(k['clcks'] / k['imprs'] * 100.0)
        except (TypeError, KeyError):
            k['ctr'] = '{0:0.02f}'.format(0.0)
        except ZeroDivisionError:
            k['ctr'] = '&infin;'

    s = sorted(summary.iterkeys())
    f, s = tee(s)
    next(s, None)
    for least, most in izip(f, s):
        current = least + datetime_interval
        while current != most:
            summary[current] = {'imprs': 0, 'clcks': 0, 'ctr': '{0:0.02f}'.format(0.0)}
            current += datetime_interval

    result = []
    for k, v in summary.iteritems():
        result.append([
            utc_tz.localize(k).astimezone(local_tz).strftime('%d.%m.%Y %H:%M') if isinstance(k, datetime)
            else k.strftime('%d.%m.%Y'),
            v.get('imprs', 0),
            v.get('clcks', 0),
#            format_decimal(v.get('imprs', 0)),
#            format_decimal(v.get('clcks', 0)),
            v['ctr']
        ])
    return jsonify({'aaData': result})

me-advert/console/templates/client/campaigns.html
{% extends 'client/frame.html' %}

{% block sub_title %}Кампании{% endblock %}
{% block nav_campaigns %}active{% endblock %}
{% block frame_header %}Кампании{% endblock %}

{% block content %}
  <div class="row-fluid">
    <div class="span12">
      <div class="box box-color box-bordered">
        <div class="box-title">
          <h3>
            <i class="icon-bar-chart"></i>
            Обзор
          </h3>
          <div class="actions">
            <a href="#" class="btn btn-mini content-refresh" id='campaigns-refresh'><i class="icon-refresh"></i></a>
          </div>
        </div>
        <div class="box-content nopadding">
          <table class="table table-hover table-nomargin dataTable table-bordered">
            <colgroup>
              <col style="width: 30%;"> {# Name of campaign #}
              <col style="width: 10%;"> {# Status #}
              <col style="width: 10%;"> {# Impressions #}
              <col style="width: 10%;"> {# Clicks #}
              <col style="width: 10%;"> {# CTR #}
            </colgroup>
            <thead>
              <tr>
                <th>Название кампании</th>
                <th>Статус</th>
                <th>Показы</th>
                <th>Клики</th>
                <th>CTR (%)</th>
              </tr>
            </thead>
            <tbody>
              {% for row in data %}
                <tr>
                  <td>
                    <a class="btn" rel="tooltip" data-placement="bottom" data-original-title="Показать отчет" href="{{ url_for('client.stats_by_campaign', campaign_id=row.campaign_id) }}"><i class="icon-bar-chart"></i></a>
                    <a href="{{ url_for('client.creatives_by_campaign', campaign_id=row.id) }}">{{ row.name|e }}</a>
                  </td>
                  <td>{{ row.state }}</td>
                  <td>{{ row.impr  if row.impr else 0 }}</td>
                  <td>{{ row.clck if row.clck else 0 }}</td>
                  <td>{{ row.ctr }}</td>
                </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
  <script>
    $(function(){
      function reload(){
        location.reload();
      }
      setTimeout(reload, dataRefreshInterval);
      $('a#campaigns-refresh').click(function(){
        setTimeout(reload, delayBeforePageReload);
      })

    })
  </script>
{%  endblock %}

me-advert/console/templates/client/creatives_by_campaign.html
{% extends 'client/frame.html' %}

{%- macro tr_cells(exp_list, row_index, row_len) %}
  <tr>
    {% for num in range(row_index * row_len, row_index * row_len + row_len) -%}
      <td>{% if exp_list[num] %}{{ exp_list[num].site }}{% endif %}</td>
    {%- endfor %}
  </tr>
{%- endmacro -%}

{% block sub_title %}Кампании{% endblock %}
{% block nav_campaigns %}active{% endblock %}
{% block frame_header %}Кампании{% endblock %}

{% block content %}
  <div class="row-fluid">
    <div class="span12">
      <div class="box box-bordered">
        <div class="box-title">
          <h3>
            <i class="icon-briefcase"></i>
            Креативы :: {{ campaign.name|e }}
          </h3>
          <div class="actions">
            <a href="" class="btn btn-mini content-refresh" id='page-refresh'><i class="icon-refresh"></i></a>
          </div>
        </div>
        <div class="box-content nopadding">
          <table class="table table-hover table-nomargin dataTable table-bordered">
            <colgroup>
              <col style="width: 35%;"> {# creative compound name #}
              <col>  {# target impressions #}
              <col>  {# # of impressions #}
              <col>  {# # of clicks #}
              <col>  {# CTR #}
              <col> {# Reach #}
            </colgroup>
            <thead>
              <tr>
                <th>Креатив</th>
                <th>Целевые показы</th>
                <th>Показы</th>
                <th>Клики</th>
                <th>CTR (%)</th>
                <th>Охват</th>
              </tr>
            </thead>
            <tbody>
              {% for row in creatives %}
                <tr>
                  <td>
                    <a class="btn" rel="tooltip" data-placement="bottom" data-original-title="Показать отчет" href="{{ url_for('client.stats_by_creative', creative_id=row.creative_id) }}"><i class="icon-bar-chart"></i></a>
                    <span>{% if row.creative_name %}{{ row.creative_name|e }} ({{ row.creative_format.get_full_name()|e }}){% else %}{{ row.creative_format.get_full_name()|e }}{% endif %}</span>
                  </td>
                  <td>{{ row.target_impr }}</td>
                  <td>{{ row.impr  if row.impr else 0 }}</td>
                  <td>{{ row.clck if row.clck else 0 }}</td>
                  <td>{{ row.ctr|safe }}</td>
                  <td>{{ row.reach }}</td>
                </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
      <div class="box box-bordered">
        <div class="box-title">
          <h3>
            <i class="icon-list"></i>
            Площадки :: {{ campaign.name|e }}
          </h3>
          <div class="actions">
            <a href="" class="btn btn-mini content-refresh" id='page-refresh'><i class="icon-refresh"></i></a>
          </div>
        </div>
        <div class="box-content nopadding">
          <table class="table table-hover table-nomargin dataTable table-bordered">
            <thead>
              <tr>
                <th>Площадка</th>
                <th>Площадка</th>
                <th>Площадка</th>
                <th>Площадка</th>
              </tr>
            </thead>
            <tbody>
              {%- set row_len = 4 -%}
              {% for row_index in range(0, (sites|count / row_len)|round(0, 'ceil')|int) -%}
                {{- tr_cells(sites, row_index, row_len) -}}
              {%- endfor %}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
  <script>
    $(function(){
      function reload(){
        location.reload();
      }
      setTimeout(reload, dataRefreshInterval);
      $('a#page-refresh').
        each(function() {
          $(this).click(function(){
          setTimeout(reload, delayBeforePageReload);
        })
      });

      $("#mytable_info").prepend('<button></button>')
    })
  </script>
{%  endblock %}

me-advert/console/templates/client/frame.html
{% extends 'frame.html' %}

{% block nav_pane %}
  <li class="{% block nav_overview %}{% endblock %}"><a href="{{ url_for('client.overview') }}">Клиент</a></li>
  <li class="{% block nav_campaigns %}{% endblock %}"><a href="{{ url_for('client.campaigns') }}">Кампании</a></li>
{% endblock %}

me-advert/console/templates/client/graph_by_campaign.html
{% extends 'client/frame.html' %}

{% block sub_title %}{{ campaign.name|e }} :: Отчет{% endblock %}
{% block nav_campaigns %}active{% endblock %}
{% block frame_header %}{{ campaign.name|e }}{% endblock %}

{% block content %}
  {% set stats_ajax_endpoint = url_for('client.stats_graph_of_campaign_ajax', campaign_id=campaign.id) %}
  {% include 'graph_body.html' %}
{% endblock %}

me-advert/console/templates/client/graph_by_creative.html
{% extends 'client/frame.html' %}

{% block sub_title %}{{ creative.campaign.name|e }} :: {{ creative.creative_format.get_full_name() }}{% endblock %}
{% block nav_campaigns %}active{% endblock %}
{% block frame_header %}{{ creative.campaign.name|e }} :: {{ creative.creative_format.get_full_name() }}{% endblock %}

{% block content %}
  {% set stats_ajax_endpoint = url_for('client.stats_graph_of_creative_ajax', creative_id=creative.id) %}
  {% set is_reach_visible = True %}
  {% include 'graph_body.html' %}
{% endblock %}

me-advert/console/templates/client/no_creatives_yet.html
{% extends 'client/frame.html' %}

{% block sub_title %}Кампании{% endblock %}
{% block nav_campaigns %}active{% endblock %}
{% block frame_header %}Кампании{% endblock %}

{% block content %}
  <div class="row-fluid">
    <div class="span12">
      <div class="box box-bordered">
        <div class="box-title">
          <h3>
            <i class="icon-briefcase"></i>
            Креативы :: {{ campaign_name|e }}
          </h3>
          <div class="actions">
            <a href="" class="btn btn-mini content-refresh" id='page-refresh'><i class="icon-refresh"></i></a>
          </div>
        </div>
        <div class="box-content nopadding">
          Для кампании ещё не создано ни одного креатива.
        </div>
      </div>
    </div>
  </div>
  <script>
    $(function(){
      function reload(){
        location.reload();
      }
      setTimeout(reload, dataRefreshInterval);
      $('a#page-refresh').each().click(function(){
        setTimeout(reload, delayBeforePageReload);
      })

    })
    $(function(){
      $("#mytable_info").prepend('<button></button>')
    })
  </script>
{%  endblock %}

me-advert/console/templates/client/overview.html
{% extends 'client/frame.html' %}

{% block sub_title %}Клиент{% endblock %}
{% block nav_overview %}active{% endblock %}
{% block frame_header %}{{ org.name|e }}{% endblock %}

{% block content %}
  <div class="lead">
    <div class="row-fluid">
      <div class="span3"><p class="text-right"><strong>Полное название</strong></p></div>
      <div class="span3"><p class="text-left">{{ org.full_name|e }}</p></div>
    </div>
    <div class="row-fluid">
      <div class="span3"><p class="text-right"><strong>Активных РК</strong></p></div>
      <div class="span3"><p class="text-left">{{ active_campaigns }} (<a href="{{ url_for('client.campaigns') }}">показать</a>)</p></div>
    </div>
    <div class="row-fluid">
      <div class="span3"><p class="text-right"><strong>Неактивных РК</strong></p></div>
      <div class="span3"><p class="text-left">{{ inactive_campaigns }} (<a href="{{ url_for('client.campaigns') }}">показать</a>)</p></div>
    </div>
    <div class="row-fluid">
      <div class="span3"><p class="text-right"><strong>Архивных РК</strong></p></div>
      <div class="span3"><p class="text-left">{{ archived_campaigns }}</p></div>
    </div>
    <div class="row-fluid">
      <div class="span3"><p class="text-right"><strong>Показов по активным РК</strong></p></div>
      <div class="span3"><p class="text-left">{{ total_impressions }}</p></div>
    </div>
    <div class="row-fluid">
      <div class="span3"><p class="text-right"><strong>Кликов по активным РК</strong></p></div>
      <div class="span3"><p class="text-left">{{ total_clicks }}</p></div>
    </div>
    <div class="row-fluid">
      <div class="span3"><p class="text-right"><strong>CTR (%) по активным РК</strong></p></div>
      <div class="span3"><p class="text-left">{{ ctr }}</p></div>
    </div>
    <div class="row-fluid">
      <div class="span3"><p class="text-right"><strong>Сотрудники</strong></p></div>
      <div class="span9"><p class="text-left">{{ staff }}</p></div>
    </div>
  </div>
{% endblock %}

me-advert/console/templates/client/stats_summary.html
{% extends 'client/frame.html' %}

{% block sub_title %}Кампании{% endblock %}
{% block nav_campaigns %}active{% endblock %}
{% block frame_header %}Кампании{% endblock %}