me-advert/console/views/stats.py
# -*- coding: utf-8 -*-

from __future__ import division

__author__ = 'ogaidukov'

from datetime import datetime, timedelta
from collections import defaultdict
from itertools import tee, izip
from flask import Blueprint
from flask import request, render_template, redirect, jsonify, url_for
from flask.ext.login import login_required, current_user
from console import utc_tz, local_tz
from console.lib.identity import manager_required
from console import redirectors
from sqlalchemy import func
from sqlalchemy.orm import joinedload
from sqlalchemy.orm.exc import NoResultFound
from commonlib.database import session
from commonlib.model import Campaign, Creative, Counter, AdLog


stats_bp = Blueprint('stats', __name__)


@stats_bp.route("/stats_by_campaign/<int:campaign_id>")
@login_required
@manager_required
def stats_by_campaign(campaign_id):
    try:
        campaign = session.query(Campaign) \
            .options(joinedload(Campaign.organization)) \
            .filter(Campaign.id == campaign_id,
                    Campaign.state != 'archived')\
            .one()
    except NoResultFound:
        return redirect(url_for(redirectors[current_user.person.role]))

    return render_template('stats/stats_by_campaign.html',
                           campaign=campaign)


@stats_bp.route("/stats_by_creative/<int:creative_id>")
@login_required
@manager_required
def stats_by_creative(creative_id):
    try:
        creative = session.query(Creative) \
            .options(joinedload(Creative.campaign,
                                Campaign.organization)) \
            .join(Campaign.creatives) \
            .filter(Creative.id == creative_id,
                    Campaign.state != 'archived')\
            .one()
    except NoResultFound:
        return redirect(url_for(redirectors[current_user.person.role]))

    return render_template('stats/stats_by_creative.html',
                           creative=creative)


@stats_bp.route("/stats_by_counter/<int:counter_id>")
@login_required
@manager_required
def stats_by_counter(counter_id):
    try:
        counter = session.query(Counter) \
            .options(joinedload(Counter.creative,
                                Creative.campaign,
                                Campaign.organization),
                     joinedload(Counter.contractor)) \
            .join(Campaign.creatives) \
            .join(Creative.counters) \
            .filter(Counter.id == counter_id,
                    Campaign.state != 'archived')\
            .one()
    except NoResultFound:
        return redirect(url_for(redirectors[current_user.person.role]))

    return render_template('stats/stats_by_counter.html',
                           counter=counter)


@stats_bp.route("/stats_by_campaign_ajax/<int:campaign_id>", methods=["GET"])
@login_required
@manager_required
def stats_by_campaign_ajax(campaign_id):
    query_template = session.query(Campaign) \
        .filter(Campaign.id == campaign_id)
    return prepare_stats(query_template)


@stats_bp.route("/stats_by_creative_ajax/<int:creative_id>", methods=["GET"])
@login_required
@manager_required
def stats_by_creative_ajax(creative_id):
    query_template = session.query(Creative) \
        .filter(Creative.id == creative_id)
    return prepare_stats(query_template)


@stats_bp.route("/stats_by_counter_ajax/<int:counter_id>", methods=["GET"])
@login_required
@manager_required
def stats_by_counter_ajax(counter_id):
    query_template = session.query(Counter) \
        .filter(Counter.id == counter_id)
    return prepare_stats(query_template)


def prepare_stats(query_template):
    start_datetime = request.args.get('start_datetime', '01.01.1970 00:00')
    end_datetime = request.args.get('end_datetime', '01.01.2970 00:00')
    try:
        start_datetime = datetime.strptime(start_datetime, '%d.%m.%Y %H:%M')
        end_datetime = datetime.strptime(end_datetime, '%d.%m.%Y %H:%M')
    except ValueError:
        return jsonify()

    scale = request.args.get('scale', 'day')
    if scale == 'hour':
        sqla_timedate_field = AdLog.date_to_hour_stamp
        datetime_interval = timedelta(hours=1)
    elif scale == 'day':
        sqla_timedate_field = AdLog.date_stamp
        datetime_interval = timedelta(days=1)
    else:
        return jsonify()

    query_template = query_template \
        .join(Campaign.creatives) \
        .join(Creative.counters) \
        .join(Counter.logs) \
        .filter(Campaign.state != 'archived',
                sqla_timedate_field.between(start_datetime, end_datetime))

    summary = defaultdict(dict)

    imprs_data = query_template \
        .with_entities(sqla_timedate_field, func.sum(AdLog.value)) \
        .filter(AdLog.record_type == 'impr') \
        .group_by(sqla_timedate_field) \
        .all()
    for k, v in imprs_data:
        if k:
            summary[k]['imprs'] = v

    clcks_data = query_template \
        .with_entities(sqla_timedate_field, func.sum(AdLog.value)) \
        .filter(AdLog.record_type == 'clck') \
        .group_by(sqla_timedate_field) \
        .all()
    for k, v in clcks_data:
        if k:
            summary[k]['clcks'] = v

    for k in summary.itervalues():
        try:
            k['ctr'] = '{0:0.02f}'.format(k['clcks'] / k['imprs'] * 100.0)
        except (TypeError, KeyError):
            k['ctr'] = '{0:0.02f}'.format(0.0)
        except ZeroDivisionError:
            k['ctr'] = '&infin;'

    s = sorted(summary.iterkeys())
    f, s = tee(s)
    next(s, None)
    for least, most in izip(f, s):
        current = least + datetime_interval
        while current != most:
            summary[current] = {'imprs': 0, 'clcks': 0, 'ctr': '{0:0.02f}'.format(0.0)}
            current += datetime_interval

    result = []
    for k, v in summary.iteritems():
        result.append([
            utc_tz.localize(k).astimezone(local_tz).strftime('%d.%m.%Y %H:%M') if isinstance(k, datetime)
            else k.strftime('%d.%m.%Y'),
            v.get('imprs', 0),
            v.get('clcks', 0),
#            format_decimal(v.get('imprs', 0)),
#            format_decimal(v.get('clcks', 0)),
            v['ctr']
        ])
    return jsonify({'aaData': result})

me-advert/console/templates/stats/stats_body.html
<div class="box-content">
  <div class="statistic-big">
    <div class="top">
      <div class="left">
        <form class="form-inline">
          <label for="start-datetime">Начало:</label>
          <input type="text" name="start-datetime" id="start-datetime" class='input-medium date-picker' {# value="{{ start_date.strftime('%d.%m.%Y 00:00') }}" #}/>
          <label for="end-datetime">Конец:</label>
          <input type="text" name="end-datetime" id="end-datetime" class='input-medium date-picker' {# value="{{ due_date.strftime('%d.%m.%Y 00:00') }}" #}/>
          <label for="summary-select">Масштаб:</label>
          <select id="summary-select" data-nosearch="true">
            <option value="day">День</option>
            <option value="hour">Час</option>
          </select>
          <button class="btn" id='graph-refresh'>Обновить</button>
        </form>
      </div>
      <div class="right"></div>
    </div>
    <table class="table table-hover table-nomargin stats-by-camp table-bordered">
      <colgroup>
        <col>  {# time period #}
        <col>  {# impressions per period #}
        <col>  {# clicks per period #}
        <col>  {# CTR #}
      </colgroup>
      <thead>
        <tr>
          <th>Период</th>
          <th>Показы</th>
          <th>Клики</th>
          <th>CTR (%)</th>
        </tr>
      </thead>
      <tbody>
      </tbody>
      <tfoot>
        <tr>
          <th style="text-align:right" >Итого:</th>
          <th></th>
          <th></th>
          <th></th>
        </tr>
      </tfoot>
    </table>
  </div>
</div>
<script>
  $(function() {
    var oTable;

    function update_ajax() {
      var ajax_url = '{{ stats_ajax_endpoint }}?start_datetime=' + $('#start-datetime').val() + '&' + 'end_datetime=' + $('#end-datetime').val() + '&' + 'scale=' + $('#summary-select').val()
      oTable.fnReloadAjax(ajax_url);
    }

    $('.date-picker').each(function () {
      $(this).appendDtpicker({
        "firstDayOfWeek": 1,
        "locale": "ru",
        "inline": false,
        "closeOnSelected": true});
    });

    $('form').submit(false);
    $('#summary-refresh').click(update_ajax);
    $('#graph-refresh').click(update_ajax);

    $('.stats-by-camp').each(function(){
        var opt = {
            "bProcessing": true,
            "bServerSide": false,
            "sAjaxSource": "{{ stats_ajax_endpoint }}",
            "sPaginationType": "full_numbers",
            "iDisplayLength": 100,
            "sDom": "<'row-fluid'<'span6'l><'span3'r><'span3 pull-right'T>>t<'row-fluid'<'span6'i><'span6'p>>",
            "sWrapper": "dataTables_wrapper form-inline",
            "aoColumns": [
              { "sType": "date-spec" },
              {},
              {},
              {},
            ],
            "oTableTools": {
              "aButtons": [ "copy", "print" ],
              "sSwfPath": "{{ url_for('static', filename='js/plugins/datatable/swf/copy_csv_xls_pdf.swf') }}"
            },
            "oLanguage":{
                "sProcessing":   "Подождите...",
                "sLengthMenu":   "_MENU_ <span>записей на страницу</span>",
                "sZeroRecords":  "Записи отсутствуют",
                "sInfo":         "Показаны с <span>_START_</span> по <span>_END_</span> из <span>_TOTAL_</span> записей",
                "sInfoEmpty":    "Записи с <span>0</span> до <span>0</span> из <span>0</span> записей",
                "sInfoFiltered": "(отфильтровано из <span>_MAX_</span> записей)",
                "sInfoPostFix":  "",
                "sSearch":       "<span>Поиск:</span>",
                "sUrl":          "",
                "oPaginate": {
                    "sFirst": "Первая",
                    "sPrevious": "Пред.",
                    "sNext": "След.",
                    "sLast": "Последняя"
                },
                "oAria": {
                    "sSortAscending":  ": активировать для сортировки столбца по возрастанию",
                    "sSortDescending": ": активировать для сортировки столбцов по убыванию"
                }
            },
            "bStateSave": true,
            "fnStateSave": function (oSettings, oData) {
                localStorage.setItem( 'dt-stat-by-camp', JSON.stringify(oData) );
            },
            "fnStateLoad": function (oSettings) {
                return JSON.parse( localStorage.getItem('dt-stat-by-camp') );
            },
            "fnFooterCallback": function ( nRow, aaData, iStart, iEnd, aiDisplay ) {
              var iTotalImprs = 0.0;
              for ( var i=0 ; i<aaData.length ; i++ )
              {
                iTotalImprs += aaData[i][1]*1.0;
              }
              var iTotalClcks = 0.0;
              for ( var i=0 ; i<aaData.length ; i++ )
              {
                iTotalClcks += aaData[i][2]*1.0;
              }
              var nCells = nRow.getElementsByTagName('th');
              nCells[1].innerHTML = parseInt(iTotalImprs);
              nCells[2].innerHTML = parseInt(iTotalClcks);
              nCells[3].innerHTML = parseFloat(Math.round(iTotalClcks*10000.0/iTotalImprs)/100.0);
            }
        };
        oTable = $(this).dataTable(opt);
        $(".dataTables_filter input").attr("placeholder", "Введите запрос...");
        $(".dataTables_length select").wrap("<div class='input-mini'></div>").chosen({
          disable_search_threshold: 9999999
        });
        $("#check_all").click(function(e){
            $('input', oTable.fnGetNodes()).prop('checked',this.checked);
        });
    });
    // force correct width for chosen
    resize_chosen();



  });
</script>

me-advert/console/templates/stats/stats_by_campaign.html
{% extends 'manager/frame.html' %}

{% block sub_title %}{{ campaign.organization.name|e }} :: {{ campaign.name|e }}{% endblock %}
{% block nav_campaigns %}active{% endblock %}
{% block frame_header %}Отчет{% endblock %}

{% block content %}
  {% set stats_ajax_endpoint = url_for('stats.stats_by_campaign_ajax', campaign_id=campaign.id) %}
  <div class="row-fluid">
    <div class="span12">
      <div class="box box-bordered">
        <div class="box-title">
          <h3>
            <i class="icon-bar-chart"></i>
            Кампания :: <a href="{{ url_for('manager.campaigns_by_org', org_id=campaign.organization.id) }}">{{ campaign.organization.name|e }}{% if campaign.organization.full_name %} ({{ campaign.organization.full_name|e }}){% endif %}</a> :: {{ campaign.name|e }}
          </h3>
          <div class="actions">
            <a href="#" class="btn btn-mini content-refresh" id='summary-refresh'><i class="icon-refresh"></i></a>
          </div>
        </div>
        {% include 'stats/stats_body.html' %}
      </div>
    </div>
  </div>
{% endblock %}

me-advert/console/templates/stats/stats_by_counter.html
{% extends 'manager/frame.html' %}

{% block sub_title %}{{ counter.creative.campaign.organization.name|e }} :: {{ counter.creative.campaign.name|e }}{% endblock %}
{% block nav_campaigns %}active{% endblock %}
{% block frame_header %}Отчет{% endblock %}

{% block content %}
  {% set stats_ajax_endpoint = url_for('stats.stats_by_counter_ajax', counter_id=counter.id) %}
  <div class="row-fluid">
    <div class="span12">
      <div class="box box-bordered">
        <div class="box-title">
          <h3>
            <i class="icon-bar-chart"></i>
            Код :: <a href="{{ url_for('manager.campaigns_by_org', org_id=counter.creative.campaign.organization.id) }}">{{ counter.creative.campaign.organization.name|e }}{% if counter.creative.campaign.organization.full_name %} ({{ counter.creative.campaign.organization.full_name|e }}){% endif %}</a> :: <a href="{{ url_for('manager.creatives_by_campaign', campaign_id=counter.creative.campaign.id) }}">{{ counter.creative.campaign.name|e }}</a> :: <a href="{{ url_for('manager.counters_by_creative', creative_id=counter.creative.id) }}">{% if counter.creative.name %}{{ counter.creative.name }} ({{ counter.creative.creative_format.get_full_name()|e }}){% else %}{{ counter.creative.creative_format.get_full_name()|e }}{% endif %}</a> :: {{ counter.contractor.name }}
          </h3>
          <div class="actions">
            <a href="#" class="btn btn-mini content-refresh" id='summary-refresh'><i class="icon-refresh"></i></a>
          </div>
        </div>
        {% include 'stats/stats_body.html' %}
      </div>
    </div>
  </div>
{% endblock %}

me-advert/console/templates/stats/stats_by_creative.html
{% extends 'manager/frame.html' %}

{% block sub_title %}{{ creative.campaign.organization.name|e }} :: {{ creative.campaign.name|e }}{% endblock %}
{% block nav_campaigns %}active{% endblock %}
{% block frame_header %}Отчет{% endblock %}

{% block content %}
  {% set stats_ajax_endpoint = url_for('stats.stats_by_creative_ajax', creative_id=creative.id) %}
  <div class="row-fluid">
    <div class="span12">
      <div class="box box-bordered">
        <div class="box-title">
          <h3>
            <i class="icon-bar-chart"></i>
            Креатив :: <a href="{{ url_for('manager.campaigns_by_org', org_id=creative.campaign.organization.id) }}">{{ creative.campaign.organization.name|e }}{% if creative.campaign.organization.full_name %} ({{ creative.campaign.organization.full_name|e }}){% endif %}</a> :: <a href="{{ url_for('manager.creatives_by_campaign', campaign_id=creative.campaign.id) }}">{{ creative.campaign.name|e }}</a> :: {% if creative.name %}{{ creative.name }} ({{ creative.creative_format.get_full_name()|e }}){% else %}{{ creative.creative_format.get_full_name()|e }}{% endif %}
          </h3>
          <div class="actions">
            <a href="#" class="btn btn-mini content-refresh" id='summary-refresh'><i class="icon-refresh"></i></a>
          </div>
        </div>
        {% include 'stats/stats_body.html' %}
      </div>
    </div>
  </div>
{% endblock %}