me-advert/console/views/manager.py
# -*- coding: utf-8 -*-

from __future__ import division

__author__ = 'ogaidukov'

from collections import defaultdict
from io import BytesIO
from werkzeug import secure_filename
from flask import request, Blueprint, render_template, redirect, escape, jsonify, url_for, make_response
from flask.ext.login import login_required, logout_user, current_user
from console import app, login_manager, redirectors
from console.views import forms
from console.lib import funcs
from console.lib.identity import manager_required
from sqlalchemy import func, or_
from sqlalchemy.orm import joinedload
from sqlalchemy.orm.exc import NoResultFound
from commonlib.database import session
from commonlib.model import Campaign, Creative, CreativeFormat, GeoCountries, GeoCities, \
    Counter, AdLog, Person, Organization, Contractor, Site

manager_bp = Blueprint('manager', __name__)


@manager_bp.route("/organizations")
@login_required
@manager_required
def organizations():
    orgs = Organization.query \
        .options(joinedload(Organization.persons)) \
        .all()
    return render_template('manager/organizations.html',
                           orgs=orgs)


@manager_bp.route("/new_organization", methods=["GET", "POST"])
@login_required
@manager_required
def new_organization():
    form = forms.NewOrganizationForm(request.form)
    if request.method == "POST" and form.validate_on_submit():
        redirect_url = request.args.get('back_url', url_for(redirectors[current_user.person.role]))
        organization = Organization(form.name.data, form.full_name.data)
        session.add(organization)
        session.commit()
        return redirect(redirect_url)
    return render_template("manager/edit_organization.html",
                           form=form,
                           type='new',
                           back_url=request.referrer if request.referrer else None)


@manager_bp.route("/edit_organization/<int:org_id>", methods=["GET", "POST"])
@login_required
@manager_required
def edit_organization(org_id):
    form = forms.EditOrganizationForm(request.form)
    organization = Organization.query.filter_by(id=org_id).first()
    if request.method == "POST" and form.validate_on_submit():
        organization.name = form.name.data
        organization.full_name = form.full_name.data
        session.commit()
        redirect_url = request.args.get('back_url', url_for(redirectors[current_user.person.role]))
        return redirect(redirect_url)
    else:
        form.name.data = organization.name
        form.full_name.data = organization.full_name
    return render_template("manager/edit_organization.html",
                           form=form,
                           type='edit',
                           back_url=request.referrer if request.referrer else None)


@manager_bp.route("/select_organizations_ajax", methods=["GET"])
@login_required
@manager_required
def select_organizations_ajax():
    def format_name(name, full_name):
        if full_name is None or full_name == u'':
            return u"{}".format(name)
        else:
            return u"{} ({})".format(name, full_name)

    query = escape(request.args.get('query'))
    like_arg = u"%{}%".format(query)
    organizations = Organization.query\
        .filter(or_(Organization.name.ilike(like_arg), Organization.full_name.ilike(like_arg))).all()
    res = map(lambda x: {'id': x.id, 'name': format_name(x.name, x.full_name)}, organizations)
    return jsonify(organizations=res)


@manager_bp.route("/organization_by_id_ajax", methods=["GET"])
@login_required
@manager_required
def organization_by_id_ajax():
    org_id = request.args.get('org_id')
    if org_id is not None and not org_id.isdigit():
        return jsonify()
    try:
        organization = Organization.query\
            .filter_by(id=org_id).one()
    except NoResultFound:
        return jsonify()
    if organization.full_name is None or organization.full_name == u'':
        name = u"{}".format(organization.name)
    else:
        name = u"{} ({})".format(organization.name, organization.full_name)
    return jsonify(id=organization.id, name=name)


@manager_bp.route("/persons")
@login_required
@manager_required
def persons():
    persons = Person.query \
        .options(joinedload(Person.organization)) \
        .all()
    return render_template('manager/persons.html',
                           persons=persons)


@manager_bp.route("/person/<int:person_id>")
@login_required
@manager_required
def person(person_id):
    persons = Person.query \
        .options(joinedload(Person.organization)) \
        .filter(Person.id == person_id) \
        .all()
    return render_template('manager/persons.html',
                           persons=persons)


@manager_bp.route("/new_person", methods=["GET", "POST"])
@login_required
@manager_required
def new_person():
    form = forms.NewPersonForm(request.form)
    if request.method == "POST" and form.validate_on_submit():
        redirect_url = request.args.get('back_url', url_for(redirectors[current_user.person.role]))
        person = Person(form.email.data, form.password.data, form.first_name.data, form.surname.data,
                        role=form.role.data, is_blocked=form.is_blocked.data)
        if form.role.data == 'customer':
            person.contractor_ref = None
            person.organization_ref = form.organization_id.data if form.organization_id.data else None
        elif form.role.data == 'contractor':
            person.contractor_ref = form.contractor_id.data if form.contractor_id.data else None
            person.organization_ref = None
        elif form.role.data == 'manager':
            person.contractor_ref = None
            person.organization_ref = None
        session.add(person)
        session.commit()
        return redirect(redirect_url)
    return render_template("manager/edit_person.html",
                           form=form,
                           type='new',
                           back_url=request.referrer if request.referrer else None)


@manager_bp.route("/edit_person/<int:person_id>", methods=["GET", "POST"])
@login_required
@manager_required
def edit_person(person_id):
    form = forms.EditPersonForm(request.form)
    person = Person.query.filter_by(id=person_id).first()
    if request.method == "POST" and form.validate_on_submit():
        person.email = form.email.data
        person.first_name = form.first_name.data
        person.surname = form.surname.data
        if form.password.data != '******':
            person.update_password(form.password.data)
        person.organization_ref = form.organization_id.data if form.organization_id.data else None
        person.role = form.role.data
        if form.role.data == 'customer':
            person.contractor_ref = None
            person.organization_ref = form.organization_id.data if form.organization_id.data else None
        elif form.role.data == 'contractor':
            person.contractor_ref = form.contractor_id.data if form.contractor_id.data else None
            person.organization_ref = None
        elif form.role.data == 'manager':
            person.contractor_ref = None
            person.organization_ref = None
        person.is_blocked = form.is_blocked.data
        session.commit()
        if form.password.data != '******' and current_user.person.id == person_id:
            logout_user()
            redirect_url = url_for(login_manager.login_view)
        else:
            redirect_url = request.args.get('back_url', url_for(redirectors[current_user.person.role]))
        return redirect(redirect_url)
    else:
        form.email.data = person.email
        form.first_name.data = person.first_name
        form.surname.data = person.surname
        form.password.data = '******'
        form.retry_password.data = '******'
        form.role.data = person.role
        form.organization_id.data = person.organization_ref
        form.contractor_id.data = person.contractor_ref
        form.is_blocked.data = person.is_blocked
    return render_template("manager/edit_person.html",
                           form=form,
                           type='edit',
                           back_url=request.referrer if request.referrer else None)


@manager_bp.route("/campaigns_all")
@login_required
@manager_required
def campaigns_all():
    min_realstart_date_query = Campaign.query \
        .with_entities(Campaign.id, func.min(Counter.realstart_date).label('min_realstart_date')) \
        .join(Creative.counters) \
        .join(Creative.campaign) \
        .group_by(Campaign.id) \
        .subquery('min_realstart_date')
    campaigns_list = session.query(Campaign, 'min_realstart_date') \
        .options(joinedload(Campaign.organization)) \
        .outerjoin(min_realstart_date_query, min_realstart_date_query.c.id == Campaign.id) \
        .filter(Campaign.state != 'archived') \
        .all()

    impressions_summary = session.query(Campaign, func.sum(AdLog.value)) \
        .join(Campaign.creatives) \
        .join(Creative.counters) \
        .join(Counter.logs) \
        .filter(AdLog.record_type == 'impr',
                Campaign.state != 'archived') \
        .group_by(Campaign) \
        .all()
    impressions_rej_geo = session.query(Campaign, func.sum(AdLog.value)) \
        .join(Campaign.creatives) \
        .join(Creative.counters) \
        .join(Counter.logs) \
        .filter(AdLog.record_type == 'impr_rej_geo',
                Campaign.state != 'archived') \
        .group_by(Campaign) \
        .all()
    impressions_rej_browser = session.query(Campaign, func.sum(AdLog.value)) \
        .join(Campaign.creatives) \
        .join(Creative.counters) \
        .join(Counter.logs) \
        .filter(AdLog.record_type == 'impr_rej_browser',
                Campaign.state != 'archived') \
        .group_by(Campaign) \
        .all()
    clicks_summary = session.query(Campaign, func.sum(AdLog.value)) \
        .join(Campaign.creatives) \

me-advert/console/views/stats.py
# -*- coding: utf-8 -*-

from __future__ import division

__author__ = 'ogaidukov'

from datetime import datetime, timedelta
from collections import defaultdict
from itertools import tee, izip
from flask import Blueprint
from flask import request, render_template, redirect, jsonify, url_for
from flask.ext.login import login_required, current_user
from console import utc_tz, local_tz
from console.lib.identity import manager_required
from console import redirectors
from sqlalchemy import func
from sqlalchemy.orm import joinedload
from sqlalchemy.orm.exc import NoResultFound
from commonlib.database import session
from commonlib.model import Campaign, Creative, Counter, AdLog


stats_bp = Blueprint('stats', __name__)


@stats_bp.route("/stats_by_campaign/<int:campaign_id>")
@login_required
@manager_required
def stats_by_campaign(campaign_id):
    try:
        campaign = session.query(Campaign) \
            .options(joinedload(Campaign.organization)) \
            .filter(Campaign.id == campaign_id,
                    Campaign.state != 'archived')\
            .one()
    except NoResultFound:
        return redirect(url_for(redirectors[current_user.person.role]))

    return render_template('stats/stats_by_campaign.html',
                           campaign=campaign)


@stats_bp.route("/stats_by_creative/<int:creative_id>")
@login_required
@manager_required
def stats_by_creative(creative_id):
    try:
        creative = session.query(Creative) \
            .options(joinedload(Creative.campaign,
                                Campaign.organization)) \
            .join(Campaign.creatives) \
            .filter(Creative.id == creative_id,
                    Campaign.state != 'archived')\
            .one()
    except NoResultFound:
        return redirect(url_for(redirectors[current_user.person.role]))

    return render_template('stats/stats_by_creative.html',
                           creative=creative)


@stats_bp.route("/stats_by_counter/<int:counter_id>")
@login_required
@manager_required
def stats_by_counter(counter_id):
    try:
        counter = session.query(Counter) \
            .options(joinedload(Counter.creative,
                                Creative.campaign,
                                Campaign.organization),
                     joinedload(Counter.contractor)) \
            .join(Campaign.creatives) \
            .join(Creative.counters) \
            .filter(Counter.id == counter_id,
                    Campaign.state != 'archived')\
            .one()
    except NoResultFound:
        return redirect(url_for(redirectors[current_user.person.role]))

    return render_template('stats/stats_by_counter.html',
                           counter=counter)


@stats_bp.route("/stats_by_campaign_ajax/<int:campaign_id>", methods=["GET"])
@login_required
@manager_required
def stats_by_campaign_ajax(campaign_id):
    query_template = session.query(Campaign) \
        .filter(Campaign.id == campaign_id)
    return prepare_stats(query_template)


@stats_bp.route("/stats_by_creative_ajax/<int:creative_id>", methods=["GET"])
@login_required
@manager_required
def stats_by_creative_ajax(creative_id):
    query_template = session.query(Creative) \
        .filter(Creative.id == creative_id)
    return prepare_stats(query_template)


@stats_bp.route("/stats_by_counter_ajax/<int:counter_id>", methods=["GET"])
@login_required
@manager_required
def stats_by_counter_ajax(counter_id):
    query_template = session.query(Counter) \
        .filter(Counter.id == counter_id)
    return prepare_stats(query_template)


def prepare_stats(query_template):
    start_datetime = request.args.get('start_datetime', '01.01.1970 00:00')
    end_datetime = request.args.get('end_datetime', '01.01.2970 00:00')
    try:
        start_datetime = datetime.strptime(start_datetime, '%d.%m.%Y %H:%M')
        end_datetime = datetime.strptime(end_datetime, '%d.%m.%Y %H:%M')
    except ValueError:
        return jsonify()

    scale = request.args.get('scale', 'day')
    if scale == 'hour':
        sqla_timedate_field = AdLog.date_to_hour_stamp
        datetime_interval = timedelta(hours=1)
    elif scale == 'day':
        sqla_timedate_field = AdLog.date_stamp
        datetime_interval = timedelta(days=1)
    else:
        return jsonify()

    query_template = query_template \
        .join(Campaign.creatives) \
        .join(Creative.counters) \
        .join(Counter.logs) \
        .filter(Campaign.state != 'archived',
                sqla_timedate_field.between(start_datetime, end_datetime))

    summary = defaultdict(dict)

    imprs_data = query_template \
        .with_entities(sqla_timedate_field, func.sum(AdLog.value)) \
        .filter(AdLog.record_type == 'impr') \
        .group_by(sqla_timedate_field) \
        .all()
    for k, v in imprs_data:
        if k:
            summary[k]['imprs'] = v

    clcks_data = query_template \
        .with_entities(sqla_timedate_field, func.sum(AdLog.value)) \
        .filter(AdLog.record_type == 'clck') \
        .group_by(sqla_timedate_field) \
        .all()
    for k, v in clcks_data:
        if k:
            summary[k]['clcks'] = v

    for k in summary.itervalues():
        try:
            k['ctr'] = '{0:0.02f}'.format(k['clcks'] / k['imprs'] * 100.0)
        except (TypeError, KeyError):
            k['ctr'] = '{0:0.02f}'.format(0.0)
        except ZeroDivisionError:
            k['ctr'] = '&infin;'

    s = sorted(summary.iterkeys())
    f, s = tee(s)
    next(s, None)
    for least, most in izip(f, s):
        current = least + datetime_interval
        while current != most:
            summary[current] = {'imprs': 0, 'clcks': 0, 'ctr': '{0:0.02f}'.format(0.0)}
            current += datetime_interval

    result = []
    for k, v in summary.iteritems():
        result.append([
            utc_tz.localize(k).astimezone(local_tz).strftime('%d.%m.%Y %H:%M') if isinstance(k, datetime)
            else k.strftime('%d.%m.%Y'),
            v.get('imprs', 0),
            v.get('clcks', 0),
#            format_decimal(v.get('imprs', 0)),
#            format_decimal(v.get('clcks', 0)),
            v['ctr']
        ])
    return jsonify({'aaData': result})

me-advert/console/templates/manager/edit_organization.html
{% extends 'manager/frame.html' %}

{% from "forms.html" import render_input_tag, field_validation_error, field_label %}

{% block sub_title %}Рекламодатели{% endblock %}
{% block nav_clients %}active{% endblock %}
{% block frame_header %}Рекламодатели{% endblock %}

{% block content %}
  <div class="row-fluid">
    <div class="span6">
      <div class="box">
        <div class="box-title">
          <h3>
            <i class="icon-user"></i>
            {{ {'new': 'Новый рекламодатель', 'edit': 'Редактировать профиль рекламодателя'}[type] }}
          </h3>
        </div>
        {% if type == 'edit' %}
          <div class="container-fluid">
            <div class="row-fluid">
              <div class="alert alert-error">
                <strong>Осторожно!</strong> Все изменения здесь тут же отобразятся в интерфейсе клиента!
              </div>
            </div>
          </div>
        {% endif %}
        <div class="box-content">
          <form action="{% if back_url %}?back_url={{ back_url }}{% endif %}" method='post' class='form-validate form-horizontal' id="organization_form">
            {{ form.hidden_tag() }}
            <div class="control-group">
              {{ field_label(form.name, 'control-label', post_label_text='*') }}
              <div class="controls">
                {{ render_input_tag(form.name, "input-block-level", "name", ext_params="data-rule-required='true' data-rule-minlength='1'") }}
                {{ field_validation_error(form, "name") }}
              </div>
            </div>
            <div class="control-group">
              {{ field_label(form.full_name, 'control-label') }}
              <div class="controls">
                {{ render_input_tag(form.full_name, "input-block-level", "first_name") }}
                {{ field_validation_error(form, "full_name") }}
              </div>
            </div>
            <span class="help-block">Поля, помеченные (*), обязательны к заполнению</span>
            <div class="form-actions">
              <input type="submit" class="btn btn-primary" value="{{ {'new': 'Создать', 'edit': 'Изменить'}[type] }}">
              <button type="button" class="btn">Отмена</button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

me-advert/console/templates/manager/edit_person.html
{% extends 'manager/frame.html' %}

{% from "forms.html" import render_input_tag, render_select_tag, field_validation_error, field_label %}

{% block sub_title %}Сотрудники{% endblock %}
{% block nav_persons %}active{% endblock %}
{% block frame_header %}Сотрудники{% endblock %}

{% block content %}
  <div class="row-fluid">
    <div class="span6">
      <div class="box">
        <div class="box-title">
          <h3>
            <i class="icon-user"></i>
            {{ {'new': 'Новый сотрудник', 'edit': 'Редактировать профиль сотрудника'}[type] }}
          </h3>
        </div>
        {% if type == 'edit' %}
          <div class="container-fluid">
            <div class="row-fluid">
              <div class="alert alert-error">
                <strong>Осторожно!</strong> Все изменения здесь тут же отобразятся в интерфейсе клиента!
              </div>
            </div>
          </div>
        {% endif %}
        <div class="box-content">
          <form action="{% if back_url %}?back_url={{ back_url }}{% endif %}" method='post' class='form-validate form-horizontal' id="person_form">
            {{ form.hidden_tag() }}
            <div class="control-group">
              {{ field_label(form.email, 'control-label ', post_label_text='*') }}
              <div class="controls">
                {{ render_input_tag(form.email, "input-block-level", "email", ext_params="data-rule-required='true' data-rule-email='true' data-rule-minlength='5'") }}
                {{ field_validation_error(form, "email") }}
              </div>
            </div>
            <div class="control-group">
              {{ field_label(form.first_name, 'control-label', post_label_text='*') }}
              <div class="controls">
                {{ render_input_tag(form.first_name, "input-block-level", "first_name", ext_params="data-rule-required='true'") }}
                {{ field_validation_error(form, "first_name") }}
              </div>
            </div>
            <div class="control-group">
              {{ field_label(form.surname, 'control-label') }}
              <div class="controls">
                {{ render_input_tag(form.surname, "input-block-level", "surname") }}
                {{ field_validation_error(form, "surname") }}
              </div>
            </div>
            <div class="control-group">
              {{ field_label(form.password, 'control-label', post_label_text='*') }}
              <div class="controls">
                {{ render_input_tag(form.password, "input-block-level", "password", ext_params="data-rule-required='true' data-rule-minlength='4'") }}
                <span class="help-block">4 &divide; 20 символа</span>
                {{ field_validation_error(form, "password") }}
              </div>
            </div>
            <div class="control-group">
              {{ field_label(form.retry_password, 'control-label', post_label_text='*') }}
              <div class="controls">
                {{ render_input_tag(form.retry_password, "input-block-level", "retry_password", ext_params="data-rule-equalTo='#password' data-rule-required='true' data-rule-minlength='4'") }}
                <span class="help-block">4 &divide; 20 символа</span>
                {{ field_validation_error(form, "retry_password") }}
              </div>
            </div>
            <div class="control-group">
              {{ field_label(form.role, 'control-label', post_label_text='*') }}
              <div class="controls">
                {{ render_select_tag(form.role, "input-block-level", "role") }}
              </div>
            </div>
            <div class="control-group" id="organization-widget">
              {{ field_label(form.organization_id, 'control-label') }}
              <div class="controls">
                {{ render_input_tag(form.organization_id, "input-block-level", "organization_id", ext_params="data-placeholder=' '") }}
                {{ field_validation_error(form, "organization_id") }}
              </div>
            </div>
            <div class="control-group" id="contractor-widget">
              {{ field_label(form.contractor_id, 'control-label') }}
              <div class="controls">
                {{ render_input_tag(form.contractor_id, "input-block-level", "contractor_id", ext_params="data-placeholder=' '") }}
                {{ field_validation_error(form, "contractor_id") }}
              </div>
            </div>
            <div class="control-group">
              {{ field_label(form.is_blocked, 'control-label') }}
              <div class="controls">
                {{ render_input_tag(form.is_blocked, "icheck-me", "is_blocked", ext_params="data-skin='square' data-color='blue'") }}
                <span class="help-block">Запретить доступ к MediaEnergy</span>
              </div>
            </div>
            <span class="help-block">Поля, помеченные (*), обязательны к заполнению</span>
            <div class="form-actions">
              <input type="submit" class="btn btn-primary" value="{{ {'new': 'Создать', 'edit': 'Изменить'}[type] }}">
              <button type="button" class="btn">Отмена</button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
  <script>
    $(function(){
    function formatResult(t) {
      return "<p>" + t.name + "</p>";
    }

    function role_change() {
      switch ($(this).val()) {
        case "contractor":
          $("#organization-widget").hide();
          $("#contractor-widget").show();
          break;
        case "customer":
          $("#organization-widget").show();
          $("#contractor-widget").hide();
          break;
        case "manager":
          $("#organization-widget").hide();
          $("#contractor-widget").hide();
          break;
      }
    }

    $("#role").each(role_change)
    $("#role").change(role_change);

    $("input#organization_id").select2({
      minimumInputLength: 1,
      multiple: false,
      allowClear: true,
      ajax: {
        url: "{{ url_for('manager.select_organizations_ajax') }}",
        dataType: 'json',
        data: function (term, page) {
          return {
            query: term
          };
        },
        results: function (data, page) {
          return {results: data.organizations};
        }
      },
      initSelection: function(element, callback) {
        var id=$(element).val();
        if (id!=="") {
          $.ajax("{{ url_for('manager.organization_by_id_ajax') }}", {
            data: {
              org_id: id
            },
            dataType: "json"
          }).done(function(data) { callback(data); });
        }
      },
      formatResult: formatResult,
      formatSelection: formatResult,
      escapeMarkup: function (m) { return m; }
    });

    $("input#contractor_id").select2({
      //minimumInputLength: 1,
      multiple: false,
      allowClear: true,
      ajax: {
        url: "{{ url_for('manager.select_contractors_ajax') }}",
        dataType: 'json',
        data: function (term, page) {
          return {
            query: term
          };
        },
        results: function (data, page) {
          return {results: data.contractors};
        }
      },
      initSelection: function(element, callback) {
        var id=$(element).val();
        if (id!=="") {
          $.ajax("{{ url_for('manager.contractor_by_id_ajax') }}", {
            data: {
              contractor_id: id
            },
            dataType: "json"
          }).done(function(data) { callback(data); });
        }
      },
      formatResult: formatResult,
      formatSelection: formatResult,
      escapeMarkup: function (m) { return m; }
    });
  })
  </script>
{% endblock %}

me-advert/console/templates/manager/frame.html
{% extends 'frame.html' %}

{% block nav_pane %}
  <li class="{% block nav_clients %}{% endblock %}"><a href="{{ url_for('manager.organizations') }}">Рекламодатели</a></li>
  <li class="{% block nav_persons %}{% endblock %}"><a href="{{ url_for('manager.persons') }}">Сотрудники</a></li>
  <li class="{% block nav_campaigns %}{% endblock %}"><a href="{{ url_for('manager.campaigns_all') }}">Кампании</a></li>
  <li class="{% block nav_contractors %}{% endblock %}"><a href="{{ url_for('manager.contractors') }}">Поставщики</a></li>
{% endblock %}

me-advert/console/templates/manager/organizations.html
{% extends 'manager/frame.html' %}

{% block sub_title %}Рекламодатели{% endblock %}
{% block nav_clients %}active{% endblock %}
{% block frame_header %}Рекламодатели{% endblock %}

{% block content %}
  <div class="row-fluid">
    <div class="span12">
      <div class="box box-bordered">
        <div class="box-title">
          <h3>
            <i class="icon-group"></i>
            Рекламодатели
          </h3>
        </div>
        <div class="box-content nopadding">
          <table class="table table-hover table-nomargin orgs table-bordered">
            <colgroup>
              <col style="width: 20%;"> {# org name #}
              <col style="width: 25%;"> {# full org name #}
              <col> {# employees #}
            </colgroup>
            <thead>
              <tr>
                <th>Рекламодатель</th>
                <th>Полное название</th>
                <th>Сотрудники</th>
              </tr>
            </thead>
            <tbody>
              {% for row in orgs %}
                <tr>
                  <td>
                    <a class="btn" rel="tooltip" data-placement="bottom" data-original-title="Редактировать данные рекламодателя" href="{{ url_for('manager.edit_organization', org_id=row.id) }}"><i class="icon-edit"></i></a>
                    <a href="{{ url_for('manager.campaigns_by_org', org_id=row.id) }}"><span>{{ row.name|e }}</span></a>
                  </td>
                  <td>{{ row.full_name|e }}</td>
                  <td>
                    {% set comma_joiner = joiner() %}
                    {% for person in row.persons -%}
                      {{ comma_joiner() }} <a href="{{ url_for('manager.person', person_id=person.id) }}">{{ person.first_name|e }} {{ person.surname|e }}</a>
                    {%- endfor %}
                  </td>
                </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
  <script>
    $(function(){
      $('.orgs').each(function(){
          var opt = {
              "sPaginationType": "full_numbers",
              "iDisplayLength": 100,
              "sDom": "<'row-fluid'<'span6'lT><'span6'f>r>t<'row-fluid'<'span6'i><'span6'p>>",
              "sWrapper": "dataTables_wrapper form-inline",
              "oTableTools": {
                "aButtons": [
                  {
                    "sExtends": "gotoURL",
                    "sButtonText": "Новый рекламодатель",
                    "sGoToURL": "{{ url_for('manager.new_organization') }}"
                  }
                ]
              },
              "oLanguage":{
                  "sProcessing":   "Подождите...",
                  "sLengthMenu":   "_MENU_ <span>записей на страницу</span>",
                  "sZeroRecords":  "Записи отсутствуют",
                  "sInfo":         "Показаны с <span>_START_</span> по <span>_END_</span> из <span>_TOTAL_</span> записей",
                  "sInfoEmpty":    "Записи с <span>0</span> до <span>0</span> из <span>0</span> записей",
                  "sInfoFiltered": "(отфильтровано из <span>_MAX_</span> записей)",
                  "sInfoPostFix":  "",
                  "sSearch":       "<span>Поиск:</span>",
                  "sUrl":          "",
                  "oPaginate": {
                      "sFirst": "Первая",
                      "sPrevious": "Пред.",
                      "sNext": "След.",
                      "sLast": "Последняя"
                  },
                  "oAria": {
                      "sSortAscending":  ": активировать для сортировки столбца по возрастанию",
                      "sSortDescending": ": активировать для сортировки столбцов по убыванию"
                  }
              },
              "bStateSave": true,
              "fnStateSave": function (oSettings, oData) {
                  localStorage.setItem( 'dt-orgs', JSON.stringify(oData) );
              },
              "fnStateLoad": function (oSettings) {
                  return JSON.parse( localStorage.getItem('dt-orgs') );
              }
          };
          var oTable = $(this).dataTable(opt);
          $(".dataTables_filter input").attr("placeholder", "Введите запрос...");
          $(".dataTables_length select").wrap("<div class='input-mini'></div>").chosen({
            disable_search_threshold: 9999999
          });
          $("#check_all").click(function(e){
              $('input', oTable.fnGetNodes()).prop('checked',this.checked);
          });
      });
      // force correct width for chosen
      resize_chosen();
    })
  </script>
{% endblock %}